/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RankingsRouteImport } from './routes/rankings'
import { Route as PlayersRouteImport } from './routes/players'
import { Route as ClubRouteImport } from './routes/club'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WeekendLeaguesIndexRouteImport } from './routes/weekend-leagues.index'
import { Route as WeekendLeaguesWlIdRouteImport } from './routes/weekend-leagues.$wlId'

const RankingsRoute = RankingsRouteImport.update({
  id: '/rankings',
  path: '/rankings',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersRoute = PlayersRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubRoute = ClubRouteImport.update({
  id: '/club',
  path: '/club',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WeekendLeaguesIndexRoute = WeekendLeaguesIndexRouteImport.update({
  id: '/weekend-leagues/',
  path: '/weekend-leagues/',
  getParentRoute: () => rootRouteImport,
} as any)
const WeekendLeaguesWlIdRoute = WeekendLeaguesWlIdRouteImport.update({
  id: '/weekend-leagues/$wlId',
  path: '/weekend-leagues/$wlId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/club': typeof ClubRoute
  '/players': typeof PlayersRoute
  '/rankings': typeof RankingsRoute
  '/weekend-leagues/$wlId': typeof WeekendLeaguesWlIdRoute
  '/weekend-leagues/': typeof WeekendLeaguesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/club': typeof ClubRoute
  '/players': typeof PlayersRoute
  '/rankings': typeof RankingsRoute
  '/weekend-leagues/$wlId': typeof WeekendLeaguesWlIdRoute
  '/weekend-leagues': typeof WeekendLeaguesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/club': typeof ClubRoute
  '/players': typeof PlayersRoute
  '/rankings': typeof RankingsRoute
  '/weekend-leagues/$wlId': typeof WeekendLeaguesWlIdRoute
  '/weekend-leagues/': typeof WeekendLeaguesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/club'
    | '/players'
    | '/rankings'
    | '/weekend-leagues/$wlId'
    | '/weekend-leagues/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/club'
    | '/players'
    | '/rankings'
    | '/weekend-leagues/$wlId'
    | '/weekend-leagues'
  id:
    | '__root__'
    | '/'
    | '/club'
    | '/players'
    | '/rankings'
    | '/weekend-leagues/$wlId'
    | '/weekend-leagues/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClubRoute: typeof ClubRoute
  PlayersRoute: typeof PlayersRoute
  RankingsRoute: typeof RankingsRoute
  WeekendLeaguesWlIdRoute: typeof WeekendLeaguesWlIdRoute
  WeekendLeaguesIndexRoute: typeof WeekendLeaguesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rankings': {
      id: '/rankings'
      path: '/rankings'
      fullPath: '/rankings'
      preLoaderRoute: typeof RankingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players': {
      id: '/players'
      path: '/players'
      fullPath: '/players'
      preLoaderRoute: typeof PlayersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/club': {
      id: '/club'
      path: '/club'
      fullPath: '/club'
      preLoaderRoute: typeof ClubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weekend-leagues/': {
      id: '/weekend-leagues/'
      path: '/weekend-leagues'
      fullPath: '/weekend-leagues/'
      preLoaderRoute: typeof WeekendLeaguesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weekend-leagues/$wlId': {
      id: '/weekend-leagues/$wlId'
      path: '/weekend-leagues/$wlId'
      fullPath: '/weekend-leagues/$wlId'
      preLoaderRoute: typeof WeekendLeaguesWlIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClubRoute: ClubRoute,
  PlayersRoute: PlayersRoute,
  RankingsRoute: RankingsRoute,
  WeekendLeaguesWlIdRoute: WeekendLeaguesWlIdRoute,
  WeekendLeaguesIndexRoute: WeekendLeaguesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
