/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RankingsRouteImport } from './routes/rankings'
import { Route as PlayersRouteImport } from './routes/players'
import { Route as ClubRouteImport } from './routes/club'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WeekendLeaguesIndexRouteImport } from './routes/weekend-leagues.index'
import { Route as PlayersIndexRouteImport } from './routes/players.index'
import { Route as WeekendLeaguesCompareRouteImport } from './routes/weekend-leagues.compare'
import { Route as WeekendLeaguesWlIdRouteImport } from './routes/weekend-leagues.$wlId'
import { Route as PlayersIdRouteImport } from './routes/players.$id'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingsRoute = RankingsRouteImport.update({
  id: '/rankings',
  path: '/rankings',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersRoute = PlayersRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubRoute = ClubRouteImport.update({
  id: '/club',
  path: '/club',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WeekendLeaguesIndexRoute = WeekendLeaguesIndexRouteImport.update({
  id: '/weekend-leagues/',
  path: '/weekend-leagues/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersIndexRoute = PlayersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlayersRoute,
} as any)
const WeekendLeaguesCompareRoute = WeekendLeaguesCompareRouteImport.update({
  id: '/weekend-leagues/compare',
  path: '/weekend-leagues/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const WeekendLeaguesWlIdRoute = WeekendLeaguesWlIdRouteImport.update({
  id: '/weekend-leagues/$wlId',
  path: '/weekend-leagues/$wlId',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersIdRoute = PlayersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PlayersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/club': typeof ClubRoute
  '/players': typeof PlayersRouteWithChildren
  '/rankings': typeof RankingsRoute
  '/settings': typeof SettingsRoute
  '/players/$id': typeof PlayersIdRoute
  '/weekend-leagues/$wlId': typeof WeekendLeaguesWlIdRoute
  '/weekend-leagues/compare': typeof WeekendLeaguesCompareRoute
  '/players/': typeof PlayersIndexRoute
  '/weekend-leagues/': typeof WeekendLeaguesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/club': typeof ClubRoute
  '/rankings': typeof RankingsRoute
  '/settings': typeof SettingsRoute
  '/players/$id': typeof PlayersIdRoute
  '/weekend-leagues/$wlId': typeof WeekendLeaguesWlIdRoute
  '/weekend-leagues/compare': typeof WeekendLeaguesCompareRoute
  '/players': typeof PlayersIndexRoute
  '/weekend-leagues': typeof WeekendLeaguesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/club': typeof ClubRoute
  '/players': typeof PlayersRouteWithChildren
  '/rankings': typeof RankingsRoute
  '/settings': typeof SettingsRoute
  '/players/$id': typeof PlayersIdRoute
  '/weekend-leagues/$wlId': typeof WeekendLeaguesWlIdRoute
  '/weekend-leagues/compare': typeof WeekendLeaguesCompareRoute
  '/players/': typeof PlayersIndexRoute
  '/weekend-leagues/': typeof WeekendLeaguesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/club'
    | '/players'
    | '/rankings'
    | '/settings'
    | '/players/$id'
    | '/weekend-leagues/$wlId'
    | '/weekend-leagues/compare'
    | '/players/'
    | '/weekend-leagues/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/club'
    | '/rankings'
    | '/settings'
    | '/players/$id'
    | '/weekend-leagues/$wlId'
    | '/weekend-leagues/compare'
    | '/players'
    | '/weekend-leagues'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/club'
    | '/players'
    | '/rankings'
    | '/settings'
    | '/players/$id'
    | '/weekend-leagues/$wlId'
    | '/weekend-leagues/compare'
    | '/players/'
    | '/weekend-leagues/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  ClubRoute: typeof ClubRoute
  PlayersRoute: typeof PlayersRouteWithChildren
  RankingsRoute: typeof RankingsRoute
  SettingsRoute: typeof SettingsRoute
  WeekendLeaguesWlIdRoute: typeof WeekendLeaguesWlIdRoute
  WeekendLeaguesCompareRoute: typeof WeekendLeaguesCompareRoute
  WeekendLeaguesIndexRoute: typeof WeekendLeaguesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rankings': {
      id: '/rankings'
      path: '/rankings'
      fullPath: '/rankings'
      preLoaderRoute: typeof RankingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players': {
      id: '/players'
      path: '/players'
      fullPath: '/players'
      preLoaderRoute: typeof PlayersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/club': {
      id: '/club'
      path: '/club'
      fullPath: '/club'
      preLoaderRoute: typeof ClubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weekend-leagues/': {
      id: '/weekend-leagues/'
      path: '/weekend-leagues'
      fullPath: '/weekend-leagues/'
      preLoaderRoute: typeof WeekendLeaguesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players/': {
      id: '/players/'
      path: '/'
      fullPath: '/players/'
      preLoaderRoute: typeof PlayersIndexRouteImport
      parentRoute: typeof PlayersRoute
    }
    '/weekend-leagues/compare': {
      id: '/weekend-leagues/compare'
      path: '/weekend-leagues/compare'
      fullPath: '/weekend-leagues/compare'
      preLoaderRoute: typeof WeekendLeaguesCompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weekend-leagues/$wlId': {
      id: '/weekend-leagues/$wlId'
      path: '/weekend-leagues/$wlId'
      fullPath: '/weekend-leagues/$wlId'
      preLoaderRoute: typeof WeekendLeaguesWlIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players/$id': {
      id: '/players/$id'
      path: '/$id'
      fullPath: '/players/$id'
      preLoaderRoute: typeof PlayersIdRouteImport
      parentRoute: typeof PlayersRoute
    }
  }
}

interface PlayersRouteChildren {
  PlayersIdRoute: typeof PlayersIdRoute
  PlayersIndexRoute: typeof PlayersIndexRoute
}

const PlayersRouteChildren: PlayersRouteChildren = {
  PlayersIdRoute: PlayersIdRoute,
  PlayersIndexRoute: PlayersIndexRoute,
}

const PlayersRouteWithChildren =
  PlayersRoute._addFileChildren(PlayersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  ClubRoute: ClubRoute,
  PlayersRoute: PlayersRouteWithChildren,
  RankingsRoute: RankingsRoute,
  SettingsRoute: SettingsRoute,
  WeekendLeaguesWlIdRoute: WeekendLeaguesWlIdRoute,
  WeekendLeaguesCompareRoute: WeekendLeaguesCompareRoute,
  WeekendLeaguesIndexRoute: WeekendLeaguesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
